### PR TITLE
add: Cards for Cart, Dark mode

### PR DESCRIPTION
**Pull request by saurabhchirde**
Screenshot 2022-02-14 at 4 16 17 PM
Screenshot 2022-02-14 at 4 16 26 PM

### CODE REVIEW

**Review by j24m — APPROVED** [review]
Your code is readable and clean, you have provided with understandable naming conventions for both classes used in css and file names. Your UI is really good , The size of cards , buttons, inputs, and the colors you have used are soothing to the eye, and for the ease of user you have provided with "On Page component links." which is smooth at the same time .
Great work, 100% good to be merged.

**Review by purohitdheeraj — APPROVED** [review]
Great Work Saurabh
Looking Great to Merge 👍

**Review by mehulsatardekar — APPROVED** [review]
Looks good to merge didn't find any issues.🚀

**Comment by saurabhchirde** [comment]
@j24m Thank you for taking out your time to write a detailed review. I am glad to know, that you liked it. 🙂

**Pull request merged**
