### PR TITLE
alerts, buttons and carbon code

### PR DESCRIPTION
**Pull request by saurabhchirde**

### CODE REVIEW

**Comment by amarphule** [comment]
Looks Good to me Some suggestions
1. Alert have button X at the right.
2. In buttons if a secondary button is disabled then it should have a meaningful className.
3. In buttons > Primary > Outlined > Secondary Outlined didn't work on hover
4. In buttons > Link > Primary text didn't work on hover.
5. Icon buttons also didn't work on hover(As a user I'm not getting a clear idea that it is clickable or not).
6. why do code snippet and scrollbar have gaps between them?

**Comment by vaibhav18matere** [comment]
Some improvements
1. Alert - background color and text color should be different, it doesn't appeal as a user. (if you want to keep it the same way then make text color of higher font weight)
2. Info alert and error alert have same font icon, you can change it for error as a cross mark.
3. Secondary button add hover - cursor 
Clean UI and good work there !

**Comment by saurabhchirde** [comment]
@amarphule, Thank you for taking out your time.

Resolved
1. Alert have button X at the right. 
- There is one more type of alert which contains a button. 
2. In buttons if a secondary button is disabled then it should have a meaningful className.
3. In buttons > Primary > Outlined > Secondary Outlined didn't work on hover
4. In buttons > Link > Primary text didn't work on hover.
5. Icon buttons also didn't work on hover(As a user I'm not getting a clear idea that it is clickable or not).
6. why do code snippet and scrollbar have gaps between them?
- It is by default in carbon, did not find any solution for this.

**Comment by saurabhchirde** [comment]
@vaibhav18matere, Thank you for taking out your time.

Resolved
1. Alert - background color and text color should be different, it doesn't appeal to a user. (if you want to keep it the same way then make text color of higher font-weight)
- Reduced the font color brightness and made it a bit darker.
2. Info alert and error alert have the same font icon, you can change it for error as a cross mark.
- I have used different icons, because of the color they were looking like same.
3. Secondary button add hover - cursor
- Resolved

**Pull request merged**
